project:
  type: website
  output-dir: docs


website:
  title: "MachineLearning"
  repo-url: https://github.com/AmalSujith7/Machine-Learning-Blog
  repo-actions: [source]
  
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/AmalSujith7
      - icon: linkedin
        href: www.linkedin.com/in/amal-sujith-4a09bb1b5
format:
  html:
    theme: solar
    css: styles.css
    
    



